---
- name: Uninstall Apache
  hosts: all

  tasks:
  - name: Uninstall apache2
    apt:
      name: apache2
      state: absent
      purge: yes
      autoremove: yes
  - name: Uninstall apache2-data 
    apt:
      name: apache2-data
      state: absent
      purge: yes
      autoremove: yes
  - name: Uninstall apache2-data 
    apt:
      name: apache2-utils
      state: absent
      purge: yes
      autoremove: yes